version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nizzro
    ports:
      - 5432:5432 #database
  web:
    build: .
    env_file: .env
    environment:
      ENVIRONMENT: DOCKER
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db