# Generated by Django 2.1.1 on 2018-09-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapter',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/adapterji'),
        ),
        migrations.AddField(
            model_name='disk',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/diski'),
        ),
        migrations.AddField(
            model_name='input',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/inputi'),
        ),
        migrations.AddField(
            model_name='kabel',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/kabli'),
        ),
        migrations.AddField(
            model_name='maticna',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/maticne'),
        ),
        migrations.AddField(
            model_name='napajalnik',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/napajalniki'),
        ),
        migrations.AddField(
            model_name='procesor',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/procesorji'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/rami'),
        ),
        migrations.AddField(
            model_name='razsiritvena',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/razsiritvene'),
        ),
        migrations.AddField(
            model_name='zaslon',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/zasloni'),
        ),
    ]
