# Generated by Django 2.1.1 on 2018-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0002_auto_20180909_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(max_length=20)),
                ('podkategorija', models.CharField(max_length=20)),
                ('image', models.ImageField(default='/media/no-image.jpg', upload_to='komponente/kategorije')),
            ],
        ),
    ]
