# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0003_racun_uporabnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='vnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=20)),
                ('kategorija', models.CharField(max_length=20)),
                ('podrobnosti', models.CharField(max_length=100)),
                ('Racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalkulator.Racun')),
            ],
        ),
    ]
