# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0005_auto_20161227_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnos',
            name='znesek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
