# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0006_vnos_znesek'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnos',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
