# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0007_vnos_datum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnos',
            name='datum',
        ),
    ]
