# Generated by Django 2.1.1 on 2018-09-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0007_drugo_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugo',
            old_name='tip',
            new_name='vrsta',
        ),
    ]
