# Generated by Django 2.1.1 on 2018-09-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0008_auto_20180913_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graficna',
            old_name='povezava',
            new_name='vodilo',
        ),
    ]
