# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0008_remove_vnos_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnos',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 29, 15, 14, 18, 984756, tzinfo=utc)),
        ),
    ]
