# Generated by Django 2.1 on 2018-08-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0010_auto_20161229_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipkovnice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrstaPrikljucka', models.CharField(max_length=20)),
                ('brezZicna', models.BooleanField(default=False)),
            ],
        ),
    ]
