# Generated by Django 2.1.1 on 2018-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0010_auto_20180916_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periferija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=20)),
                ('ime', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
                ('image', models.ImageField(default='/media/no-image.jpg', upload_to='komponente/tiskalniki')),
            ],
        ),
    ]
