# Generated by Django 2.1.1 on 2018-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0011_periferija'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficna',
            name='izhod',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
