# Generated by Django 2.1.1 on 2018-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0012_graficna_izhod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komponenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('image', models.ImageField(default='/media/no-image.jpg', upload_to='komponente/komponente')),
            ],
        ),
    ]
