# Generated by Django 2.1.1 on 2018-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0013_komponenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponenta',
            name='link',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
