# Generated by Django 2.1 on 2018-08-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0014_tipkovnice_znamka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesorji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('podnozje', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
    ]
