# Generated by Django 2.1.1 on 2018-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0014_komponenta_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posiljatelj', models.CharField(max_length=20)),
                ('administrator', models.CharField(max_length=20)),
            ],
        ),
    ]
