# Generated by Django 2.1 on 2018-08-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0015_procesorji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komponenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='racun1',
            name='uporabnik',
        ),
        migrations.DeleteModel(
            name='Racun1',
        ),
        migrations.AddField(
            model_name='tipkovnice',
            name='vrsta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kalkulator.Komponenta'),
        ),
    ]
