# Generated by Django 2.1 on 2018-08-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0016_auto_20180821_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesorji',
            name='vrsta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kalkulator.Komponenta'),
        ),
    ]
