# Generated by Django 2.1 on 2018-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0018_auto_20180823_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graficne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('pomnilnik', models.CharField(max_length=20)),
                ('povezava', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=100)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Procesorji',
        ),
        migrations.AddField(
            model_name='tipkovnice',
            name='kolicina',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
