# Generated by Django 2.1 on 2018-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0019_auto_20180825_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficne',
            name='model',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
