# Generated by Django 2.1 on 2018-08-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0020_graficne_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graficne',
            new_name='Graficna',
        ),
        migrations.RenameModel(
            old_name='Tipkovnice',
            new_name='Tipkovnica',
        ),
        migrations.RemoveField(
            model_name='racun',
            name='uporabnik',
        ),
        migrations.RemoveField(
            model_name='vnos',
            name='racun',
        ),
        migrations.DeleteModel(
            name='Racun',
        ),
        migrations.DeleteModel(
            name='vnos',
        ),
    ]
