# Generated by Django 2.1 on 2018-08-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0021_auto_20180826_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('podnozje', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
    ]
