# Generated by Django 2.1 on 2018-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0024_zvocna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Napajalnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('moc', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
    ]
