# Generated by Django 2.1 on 2018-08-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0025_napajalnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('prikljucek', models.CharField(max_length=20)),
                ('povezava', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
    ]
