# Generated by Django 2.1 on 2018-09-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0027_disk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipkovnica',
            name='opis',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
