# Generated by Django 2.1 on 2018-09-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0028_tipkovnica_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='miska',
            name='opis',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
