# Generated by Django 2.1 on 2018-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0030_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mrezna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('prikljucek', models.CharField(max_length=20)),
                ('vrsta', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
    ]
