# Generated by Django 2.1 on 2018-09-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0032_zaslon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazsiritvenaKartica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('vrsta', models.CharField(max_length=20)),
                ('prikljucek', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Mrezna',
        ),
    ]
