# Generated by Django 2.1 on 2018-09-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0033_auto_20180905_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RazsiritvenaKartica',
            new_name='Razsiritvena',
        ),
    ]
