# Generated by Django 2.1 on 2018-09-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0034_auto_20180905_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='razsiritvena',
            name='model',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
