# Generated by Django 2.1 on 2018-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0038_zaslon_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znamka', models.CharField(max_length=20)),
                ('prikljucek', models.CharField(max_length=20)),
                ('povezava', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Miska',
        ),
        migrations.DeleteModel(
            name='Tipkovnica',
        ),
    ]
