# Generated by Django 2.1 on 2018-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0040_input_vrsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='napajalnik',
            name='vrsta',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
