# Generated by Django 2.1 on 2018-09-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0041_napajalnik_vrsta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=20)),
                ('znamka', models.CharField(max_length=20)),
                ('voltaza', models.CharField(max_length=20)),
                ('amperaza', models.CharField(max_length=20)),
                ('opis', models.CharField(max_length=20)),
                ('kolicina', models.CharField(max_length=20)),
            ],
        ),
    ]
