# Generated by Django 2.1 on 2018-09-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0042_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapter',
            name='moc',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
