# Generated by Django 2.1.1 on 2018-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0042_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficna',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='komponente/graficne'),
        ),
    ]
