# Generated by Django 2.1.1 on 2018-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0043_graficna_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graficna',
            name='image',
            field=models.ImageField(default='/media/no-image.jpg', upload_to='media/komponente/graficne'),
        ),
    ]
